# Generated by Django 5.2.4 on 2025-07-23 01:08

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('phone', models.CharField(max_length=20, verbose_name='핸드폰번호')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('reply_type', models.CharField(choices=[('email', '메일'), ('sms', '문자')], default='email', max_length=10, verbose_name='답변받기 선택')),
                ('agree_privacy', models.BooleanField(default=True, verbose_name='개인정보 동의')),
                ('reply_content', models.TextField(blank=True, verbose_name='답변 내용')),
                ('is_replied', models.BooleanField(default=False, verbose_name='답변 완료')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='답변일')),
            ],
            options={
                'verbose_name': '상담문의',
                'verbose_name_plural': '상담문의',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='메인 타이틀')),
                ('subtitle', models.CharField(max_length=200, verbose_name='서브 타이틀')),
                ('description', models.TextField(verbose_name='설명')),
                ('primary_button_text', models.CharField(default='분양정보 보기', max_length=50, verbose_name='주요 버튼 텍스트')),
                ('primary_button_link', models.CharField(default='#sales', max_length=200, verbose_name='주요 버튼 링크')),
                ('secondary_button_text', models.CharField(default='상담 신청', max_length=50, verbose_name='보조 버튼 텍스트')),
                ('secondary_button_link', models.CharField(default='#contact', max_length=200, verbose_name='보조 버튼 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '히어로 배너',
                'verbose_name_plural': '히어로 배너',
            },
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='팝업 제목')),
                ('content', models.TextField(verbose_name='팝업 내용')),
                ('image', models.ImageField(blank=True, upload_to=main.models.get_upload_path, verbose_name='팝업 이미지')),
                ('width', models.IntegerField(default=400, verbose_name='팝업 너비')),
                ('height', models.IntegerField(default=300, verbose_name='팝업 높이')),
                ('button_text', models.CharField(default='닫기', max_length=50, verbose_name='버튼 텍스트')),
                ('button_position', models.CharField(default='center', max_length=20, verbose_name='버튼 위치')),
                ('link_url', models.CharField(blank=True, max_length=200, verbose_name='링크 URL')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='새 탭에서 열기')),
                ('start_date', models.DateTimeField(verbose_name='시작일')),
                ('end_date', models.DateTimeField(verbose_name='종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '팝업',
                'verbose_name_plural': '팝업',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='설문 제목')),
                ('description', models.TextField(verbose_name='설문 설명')),
                ('start_date', models.DateTimeField(verbose_name='시작일')),
                ('end_date', models.DateTimeField(verbose_name='종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '설문조사',
                'verbose_name_plural': '설문조사',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('user_agent', models.TextField(verbose_name='사용자 에이전트')),
                ('page_visited', models.CharField(max_length=200, verbose_name='방문 페이지')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='방문 시간')),
            ],
            options={
                'verbose_name': '방문자 로그',
                'verbose_name_plural': '방문자 로그',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.get_upload_path, verbose_name='배너 이미지')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.herobanner')),
            ],
            options={
                'verbose_name': '히어로 이미지',
                'verbose_name_plural': '히어로 이미지',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SalesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('84A', '84A 타입'), ('84B', '84B 타입')], max_length=10, verbose_name='타입')),
                ('price_per_pyeong', models.CharField(max_length=50, verbose_name='평당 가격')),
                ('area', models.CharField(max_length=50, verbose_name='전용면적')),
                ('households', models.CharField(max_length=50, verbose_name='세대수')),
                ('floors', models.CharField(max_length=50, verbose_name='층수')),
                ('parking', models.CharField(max_length=50, verbose_name='주차')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '분양정보',
                'verbose_name_plural': '분양정보',
                'unique_together': {('type',)},
            },
        ),
        migrations.CreateModel(
            name='SalesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='이미지 제목')),
                ('image', models.ImageField(upload_to=main.models.get_upload_path, verbose_name='평면도 이미지')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.salesinfo')),
            ],
            options={
                'verbose_name': '분양 이미지',
                'verbose_name_plural': '분양 이미지',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('overview', '프로젝트 개요'), ('features', '입지환경'), ('site_plan', '단지배치도'), ('sales', '분양정보'), ('gallery', '갤러리')], max_length=20, verbose_name='섹션')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('subtitle', models.TextField(verbose_name='서브 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '섹션 콘텐츠',
                'verbose_name_plural': '섹션 콘텐츠',
                'unique_together': {('section',)},
            },
        ),
        migrations.CreateModel(
            name='SectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='카드 제목')),
                ('subtitle', models.TextField(verbose_name='카드 서브 제목')),
                ('icon', models.CharField(default='📋', max_length=50, verbose_name='아이콘')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main.sectioncontent')),
            ],
            options={
                'verbose_name': '섹션 카드',
                'verbose_name_plural': '섹션 카드',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='이미지 제목')),
                ('image', models.ImageField(upload_to=main.models.get_upload_path, verbose_name='이미지')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.sectioncontent')),
            ],
            options={
                'verbose_name': '섹션 이미지',
                'verbose_name_plural': '섹션 이미지',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='질문')),
                ('question_type', models.CharField(choices=[('multiple_choice', '객관식'), ('checkbox', '다중선택'), ('text', '주관식')], max_length=20, verbose_name='질문 타입')),
                ('allow_multiple', models.BooleanField(default=False, verbose_name='다중 답변 허용')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_required', models.BooleanField(default=True, verbose_name='필수 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.survey')),
            ],
            options={
                'verbose_name': '설문 질문',
                'verbose_name_plural': '설문 질문',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200, verbose_name='선택지')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.surveyquestion')),
            ],
            options={
                'verbose_name': '설문 선택지',
                'verbose_name_plural': '설문 선택지',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_name', models.CharField(max_length=100, verbose_name='응답자 이름')),
                ('respondent_email', models.EmailField(blank=True, max_length=254, verbose_name='응답자 이메일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.survey')),
            ],
            options={
                'verbose_name': '설문 응답',
                'verbose_name_plural': '설문 응답',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='답변 텍스트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_options', models.ManyToManyField(blank=True, to='main.surveyoption', verbose_name='선택된 옵션')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.surveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.surveyresponse')),
            ],
            options={
                'verbose_name': '설문 답변',
                'verbose_name_plural': '설문 답변',
            },
        ),
    ]
