# Generated by Django 5.2.4 on 2025-07-23 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionimage',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modal_images', to='main.sectioncard', verbose_name='연결된 카드'),
        ),
    ]
