# Generated by Django 5.2.4 on 2025-07-23 05:24

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sectionimage_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='이미지 제목')),
                ('image', models.ImageField(upload_to=main.models.get_upload_path, verbose_name='갤러리 이미지')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '갤러리 이미지',
                'verbose_name_plural': '갤러리 이미지',
                'ordering': ['order'],
            },
        ),
    ]
