# Generated by Django 5.2.4 on 2025-07-23 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='카드 타이틀')),
                ('subtitle', models.CharField(max_length=200, verbose_name='카드 서브타이틀')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '갤러리 카드',
                'verbose_name_plural': '갤러리 카드',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='이미지 제목'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.gallerycard', verbose_name='연결 카드'),
        ),
    ]
